name: build and run
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build the program
        run: mkdir build && cmake -B build -S . && cmake --build build

      - uses: actions/upload-artifact@v4
        with: 
          name: binaries
          path: |
            build/main
            build/tests

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests

  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 300 10000

