name: build and run
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Build the program
        run: mkdir build && cmake -B build -S . && cmake --build build

      - uses: actions/upload-artifact@v4
        with: 
          name: binaries
          path: |
            build/main
            build/tests
            build/benchmarks


  tests:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests


  run:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 300 10000


  benchmark:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x benchmarks && ./benchmarks

  documentation:
    needs: [build, tests, run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages


      - name: Deploy to GitHub Pages
        run: |
          rsync -av --delete docs/ gh-pages/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/${{ github.repository }} gh-pages
